sbatch run_paper_llm.sh codebert modernbert_large
sbatch run_paper_llm.sh codellama_34b codellama_python_34b
sbatch run_paper_llm.sh codellama_instruct_34b codellama_python_7b
sbatch run_paper_llm.sh llama_3_1_8b llama_3_3_70b_instruct
sbatch run_paper_llm.sh codestral_22b mixtral_8x7b
sbatch run_paper_llm.sh jina_embed_code jina_embed_code_1_5b
sbatch run_paper_llm.sh yi_coder_9b yi_coder_1_5b
sbatch run_paper_llm.sh nomic_embed_code sfr_embedding_code_2b_r